<?php


namespace core\user\controllers;


use core\base\exceptions\RouteException;

class CatalogController extends BaseUser
{
    protected function inputData()
    {
        parent::inputData(); // TODO: Change the autogenerated stub

        /*
         * ForPrint presentation-only catalog entry state.
         *
         * Consume the namespaced UI request here, then remove it before
         * business filter/order/pagination logic reads or republishes GET.
         */
        $catalogUiRequest = $_GET['fp_ui'] ?? null;
        $catalogInitialPanel = (
            is_string($catalogUiRequest)
            && $catalogUiRequest === 'filters'
        ) ? 'filters' : '';

        unset($_GET['fp_ui']);

        $catalogDefaultQuantity = (int)(
            $this->set['catalog_default_quantity'] ?? 12
        );

        if ($catalogDefaultQuantity < 1 || $catalogDefaultQuantity > 60) {
            $catalogDefaultQuantity = 12;
        }

        $quantities = array_values(array_unique([
            3,
            6,
            12,
            21,
            30,
            $catalogDefaultQuantity,
        ]));
        sort($quantities, SORT_NUMERIC);

        $requestedQuantity = $this->clearNum($_GET['quantity'] ?? 0);

        if ($requestedQuantity >= 1 && $requestedQuantity <= 60) {
            $_SESSION['quantities'] = $requestedQuantity;
        } elseif (
            empty($_SESSION['quantities'])
            || (int)$_SESSION['quantities'] < 1
            || (int)$_SESSION['quantities'] > 60
        ) {
            $_SESSION['quantities'] = $catalogDefaultQuantity;
        }


        $data = [];

        if (!empty($this->parameters['alias'])){

            $data = $this->model->get('catalog', [

                'where' => ['alias' => $this->parameters['alias'], 'visible' => 1],

                'limit' => 1

            ]);

            if (!$data){

                throw new RouteException('Товари по даному запиту не знайдені - ' . $this->parameters['alias']);

            }

            $data = $data[0];


            }

            $where = ['visible' => 1];

            if ($data){

                $where['parent_id'] = $data['id'];
            }else{

                $data['name'] = 'Каталог';

        }


        $catalogFilters = $catalogPrices = $orderDb = null;

        $order = $this->createCatalogOrder($orderDb);

        $operand = $this->checkFilters($where);

        $goods = $this->model->getGoods([
                'where' => $where,

                'operand' => $operand,

                'order' => $orderDb['order'],

                'order_direction' => $orderDb['order_direction'],

                'pagination' => [

                    'qty' => $_SESSION['quantities'] ?? QTY,

                    'page' => $this->clearNum($_GET['page'] ?? 1) ? : 1

                ],

            ], $catalogFilters, $catalogPrices);

        $pages = $this->model->getPagination();

        /*
         * FP_CATALOG_CANONICAL_PAGINATION_V0_1
         *
         * A clean, non-empty page > 1 is a distinct crawlable pagination
         * document and therefore canonicalizes to itself. page=1,
         * out-of-range pages, and sort/filter/quantity combinations retain
         * the shared queryless canonical policy.
         */
        $canonicalPageRaw = $_GET['page'] ?? null;
        $canonicalPage = (
            is_scalar($canonicalPageRaw)
            && preg_match(
                '/^\d+$/D',
                trim((string)$canonicalPageRaw)
            )
        )
            ? (int)$canonicalPageRaw
            : 0;

        if (
            $canonicalPage > 1
            && !empty($goods)
            && count($_GET) === 1
            && array_key_exists('page', $_GET)
        ) {
            $this->canonicalQuery = [
                'page' => $canonicalPage,
            ];
        }

        /* ForPrint visible catalog navigation v0.6.43 */
        $catalogCategories = [];
        $catalogGoodsCounts = [];

        try {
            $catalogGoodsRows = $this->model->get('goods', [
                'fields' => ['parent_id'],
                'where' => ['visible' => 1],
            ]) ?: [];

            foreach ($catalogGoodsRows as $catalogGoodsRow) {
                $catalogParentId = (int)($catalogGoodsRow['parent_id'] ?? 0);

                if ($catalogParentId < 1) {
                    continue;
                }

                $catalogGoodsCounts[$catalogParentId] =
                    ($catalogGoodsCounts[$catalogParentId] ?? 0) + 1;
            }

            $catalogCategories = $this->model->get('catalog', [
                'fields' => ['id', 'name', 'alias', 'menu_position'],
                'where' => ['visible' => 1],
                'order' => ['menu_position', 'id'],
                'order_direction' => ['ASC', 'ASC'],
            ]) ?: [];

            foreach ($catalogCategories as &$catalogCategory) {
                $catalogCategoryId = (int)($catalogCategory['id'] ?? 0);
                $catalogCategory['goods_count'] =
                    $catalogGoodsCounts[$catalogCategoryId] ?? 0;
            }
            unset($catalogCategory);
        } catch (\Throwable $error) {
            $catalogCategories = [];
        }

            return compact(
                'data',
                'goods',
                'catalogFilters',
                'catalogPrices',
                'catalogCategories',
                'catalogInitialPanel',
                'order',
                'quantities',
                'pages'
            );

    }

    protected function checkFilters(&$where){

        $dbWhere = [];

        $dbOperand = [];

        if(isset($_GET['min_price'])){

            $dbWhere['price'] = $this->clearNum($_GET['min_price']);

            $dbOperand[] = '>=';

        }

        if(isset($_GET['max_price'])){

            $dbWhere[' price'] = $this->clearNum($_GET['max_price']); // [' price'] - is correct video 132

            $dbOperand[] = '<=';

        }

        if (!empty($_GET['filters']) && is_array($_GET['filters'])){

            $subFiltersQuery = $this->setFilters();

            if ($subFiltersQuery){

                $dbWhere['id'] = $subFiltersQuery;

                $dbOperand[] = 'IN';

            }

        }

        $where = array_merge($dbWhere, $where);


        $dbOperand[] = '=';

        return $dbOperand;

    }

    protected function setFilters(){

     foreach ($_GET['filters'] as $key=>$item){

         $_GET['filters'][$key] = $this->clearNum($item);



     if (!$_GET['filters'][$key]){

         unset($_GET['filters'][$key]);

         continue;

            }

        $other = array_search($_GET['filters'][$key], $_GET['filters']);

     if ($other !== false && $other !== $key)

         unset($_GET['filters'][$key]);

         }

        $res = $this->model->get('filters_categories', [
         'operand' => ['IN'],

         'join' => [

             'filters' => [
                 'where' => ['id' => 'SELECT DISTINCT id FROM filters WHERE id IN ('. implode(',', $_GET['filters']) .')'],
//                 'where' => ['id' => implode(',', $_GET['filters'])],
                 'operand' => ['IN'],
                 'fields' => ['id'],
                 'on' => ['id', 'parent_id']
             ]
         ],

         'join_structure' => true,
//            'return_query' => true

         ]);

     if ($res){

         $arr = [];

         $c = 0;

         foreach ($res as $item){

             if (isset($item['join']['filters'])){

                 $arr[$c] = array_column($item['join']['filters'], 'id');

                 $c++;

             }

         }

         $resArr = $this->crossDiffArr($arr);

         if($resArr){

             $queryStr = '';

             $filtersCount = 0;

             foreach ($resArr as $key=>$item){

                 !$filtersCount && $filtersCount = count($item);

                 $queryStr .= ' filters_id IN ('. implode(',' , $item) . ')' . (isset($resArr[$key+1]) ? ' OR ' : '');

             }

             return 'SELECT goods_id FROM goods_filters WHERE  ' . $queryStr .
                    ' GROUP BY goods_id HAVING COUNT(goods_id) >= ' . $filtersCount;

         }

     }

     return '';



    }

    protected function crossDiffArr($arr, $counter = 0){

        if (count($arr) === 1){

            return array_chunk(array_shift($arr), 1);

        }

        if ($counter === count($arr)-1)

            return $arr[$counter];

            $buffer = $this->crossDiffArr($arr, $counter + 1);

            $res = [];

            foreach ($arr[$counter] as $a){

                foreach ($buffer as $b){

                    $res[] = is_array($b) ? array_merge([$a], $b) : [$a, $b];
                }

            }

            return $res;

        }

    protected function createCatalogOrder(&$orderDb){

        $order = [
            'Ціні' => 'price_asc',
            'Назві' => 'name_asc'
        ];

        $allowedOrders = [
            'menu_position_asc' => ['menu_position', 'ASC'],
            'price_asc' => ['price', 'ASC'],
            'price_desc' => ['price', 'DESC'],
            'name_asc' => ['name', 'ASC'],
            'name_desc' => ['name', 'DESC'],
        ];

        $requestedOrder = trim((string)(
            $_GET['order']
            ?? ($this->set['catalog_default_order'] ?? 'menu_position_asc')
        ));

        if (!isset($allowedOrders[$requestedOrder])) {
            $requestedOrder = 'menu_position_asc';
        }

        [$selectedField, $selectedDirection] = $allowedOrders[$requestedOrder];

        $orderDb = [
            'order' => [$selectedField, 'id'],
            'order_direction' => [$selectedDirection, 'ASC'],
        ];

        foreach ($order as $label => $fallbackOrder) {
            [$field] = explode('_', $fallbackOrder, 2);

            if ($field === $selectedField) {
                $order[$label] = $field
                    . '_'
                    . ($selectedDirection === 'ASC' ? 'desc' : 'asc');
            }
        }

        return $order;

    }

}
