<?php


namespace core\user\controllers;

use core\base\exceptions\RouteException;

class knowelegesController extends BaseUser
{
 protected function inputData()
 {
     parent::inputData(); // TODO: Change the autogenerated stub

     echo "helllo";

     $data = [];

     if (!empty($this->parameters['alias'])){

         $data = $this->model->get('catalog', [

             'where' => ['alias' => $this->parameters['alias'], 'visible' => 1],

             'limit' => 1

         ]);

         if (!$data){

             throw new RouteException('Товари по даному запиту не знайдені - ' . $this->parameters['alias']);

         }

         $data = $data[0];


     }

     $where = ['visible' => 1];

     if ($data){

         $where['parent_id'] = $data['id'];
     }else{

         $data['name'] = 'Каталог';

     }

 }
}
