<?php


namespace core\user\controllers;


use Composer\Repository\InstalledFilesystemRepository;
use core\admin\models\UserModel;
use core\base\exceptions\RouteException;
use core\user\helpers\ValidationHelper;

class LoginController extends BaseUser
{

    use ValidationHelper;

    protected function inputData()
    {
        parent::inputData(); // TODO: Change the autogenerated stub

        if (!empty($this->parameters['alias'])){

            switch ($this->parameters['alias']){

                case 'registration':

                    $this->registration();

                    break;

                case 'login':

                    $this->login();

                    break;

                case 'logout':

                    UserModel::instance()->logout();

                    $this->redirect(PATH);

                    break;

            }
        }

        throw new RouteException('Упс, здається такої сторінки не знайдено.');

    }

    protected function login(){

        $login = $this->clearStr($_POST['login'] ?? '');

        $password = $this->clearStr($_POST['password'] ?? '');

        if(!$login || !$password){

            $this->sendError('Будь ласка введіть коректні данні для входу на сайт');
        }

        $_POST['password'] = md5($password);

        $res = $this->model->get('visitors', [

                'where' => ['email' => $login, 'password' => $password],

                'limit' => 1

            ]
        );

        if (!$res){

            $this->sendError('Упс, здаеться ви ввели не коректні данні для входу на сайт');
        }

        if (UserModel::instance()->checkUser($res[0 ]['id'])){

            $this->sendSuccess('Вітаемо вас - ' . $res[0]['name']);
        }

        $this->sendError('Упс, здаеться щось пішло не так, спробуйте ще раз. Або зателефонуйте менеджеру ждя усуненя проблем :)');
    }

    protected function registration() : void
    {

        if (!$this->isPost()) {

            throw new RouteException('Упс, здається такої сторінки не знайдено.');
        }

        $_POST['password'] = trim($_POST['password'] ?? '');

        $_POST['confirm_password'] = trim($_POST['confirm_password'] ?? '');

        if ($this->userData && !$_POST['password']) {

            unset($_POST['password']);
        }elseif (!$this->userData && !trim($_POST['password'])){

            $this->sendError('Будь ласка, заповніть поле пароль');
        }

        if (isset($_POST['password']) && $_POST['password'] !== $_POST['confirm_password']) {

            $this->sendError('Здається, ваші паролі не співпадають');

        }

        unset($_POST['confirm_password']);

        $validation = [

            'name' => [
                'translate' => 'Ваше ім`я',
                'methods' => ['emptyField']
            ],
            'phone' => [
                'translate' => 'Телефон',
                'methods' => ['emptyField', 'phoneField', 'numericField']
            ],
            'email' => [
                'translate' => 'Ваша почтова скринька',
                'methods' => ['emptyField', 'emailField']

            ],
        ];

        foreach ($_POST as $key => $item) {

            if (!empty($validation[$key]['methods'])) {

                foreach ($validation[$key]['methods'] as $method) {

                    $_POST[$key] = $item = $this->$method($item, $validation[$key]['translate'] ?? $key);
                }
            }
        }

        $where = [

            'phone' => $_POST['phone'],
            'email' => $_POST['email'],

        ];

        $condition[] = 'OR';

        $res = $this->model->get('visitors', [

            'where' => $where,
            'condition' => $condition,
            'limit' => 1
        ]);

        if ($res){

            $res = $res[0];

            if(empty($this->userData) || $this->userData['id']!== $res['id']){

                $field = $res['phone'] === $_POST['phone'] ? 'телефон': 'email';

                $this->sendError('Упс, такий ' . $field . ' вже зареестрований');

            }

        }

        if (!empty($_POST['password'])){

            $_POST['password'] = md5($_POST['password']);

        }

        if ($this->userData){

            $this->model->edit('visitors', [

                'where' => ['id' => $this->userData['id']]
            ]);

            $id = $this->userData['id'];

        }else{

            $id = $this->model->add('visitors', [

                'return_id' => true
            ]);
        }


        if (!empty($id)){

            if (UserModel::instance()->checkUser($id)){

                $message = !$this->userData ? 'Супер!, ви пройшли реестрацію успішно, вітаю вас - ' . $_POST['name'] : 'Інформація успішно змінена';



                $this->sendSuccess( $message);
            }

        }

        $this->sendError('Упс, здаеться щось пішло не так, спробуйте ще раз. Або зателефонуйте менеджеру ждя усуненя проблем :)');
    }
}
