<?php


namespace core\user\controllers;


use core\base\exceptions\RouteException;

class ProductController extends BaseUser
{

    protected function inputData()
    {
        parent::inputData(); // TODO: Change the autogenerated stub

        if (empty($this->parameters['alias'])){

            throw new RouteException('Упссс здається товар відсутній');

        }

        $data = $this->model->getGoods([

            'where' => ['alias' => $this->parameters['alias'],

                        'visible' => 1

                         ],

        ]);

        if (!$data){

            throw new RouteException('Упссс за данним посиланням товар відсутній' . $this->parameters['alias']);

        }

        $data = array_shift($data);

        $deliveryInfo = $this->model->get('information',[

           'where' => ['visible'=> 1, 'name' => 'Доставка', ' name' => 'Оплата'],
            'operand' => ['=','%LIKE%'],
            'condition' => ['AND', 'OR'],
            'limit' => 1

        ]);

        $deliveryInfo && $deliveryInfo = $deliveryInfo[0];

        $relatedGoods = [];
        $relatedGoods = [];

        if (!empty($data['related_goods_ids'])) {
            $relatedIds = preg_split('/[,\s;]+/', (string)$data['related_goods_ids'], -1, PREG_SPLIT_NO_EMPTY);
            $relatedIds = array_values(array_unique(array_filter(array_map('intval', $relatedIds))));

            if ($relatedIds) {
                $relatedPool = $this->model->get('goods', [
                    'where' => ['visible' => 1],
                    'limit' => 500,
                ]);

                $relatedById = [];

                if (!empty($relatedPool) && is_array($relatedPool)) {
                    foreach ($relatedPool as $relatedItem) {
                        if (!empty($relatedItem['id'])) {
                            $relatedById[(int)$relatedItem['id']] = $relatedItem;
                        }
                    }
                }

                foreach ($relatedIds as $relatedId) {
                    if ($relatedId === (int)($data['id'] ?? 0)) {
                        continue;
                    }

                    if (isset($relatedById[$relatedId])) {
                        $relatedGoods[] = $relatedById[$relatedId];
                    }
                }
            }
        }


        return compact('data', 'deliveryInfo', 'relatedGoods');

    }

}
