<?php


namespace core\user\controllers;


use core\base\exceptions\RouteException;

class ProductController extends BaseUser
{

    protected function inputData()
    {
        parent::inputData(); // TODO: Change the autogenerated stub

        if (empty($this->parameters['alias'])){

            throw new RouteException('Упссс здається товар відсутній');

        }

        $data = $this->model->getGoods([

            'where' => ['alias' => $this->parameters['alias'],

                        'visible' => 1

                         ],

        ]);

        if (!$data){

            throw new RouteException('Упссс за данним посиланням товар відсутній' . $this->parameters['alias']);

        }

        $data = array_shift($data);

        $deliveryInfo = $this->model->get('information',[

           'where' => ['visible'=> 1, 'name' => 'Доставка', ' name' => 'Оплата'],
            'operand' => ['=','%LIKE%'],
            'condition' => ['AND', 'OR'],
            'limit' => 1

        ]);

        $deliveryInfo && $deliveryInfo = $deliveryInfo[0];

        return compact('data', 'deliveryInfo');

    }

}
