<?php


namespace core\user\controllers;


use core\user\models\Model;

class SearchController extends BaseUser
{
    protected function inputData()
    {
        parent::inputData(); // TODO: Change the autogenerated stub



        $goods = $this->search();

        $pages = $this->model->getPagination();

        $this->template = TEMPLATE . 'catalog';

        $dontShowAside = true;

        $data['name'] = 'Результати пошуку ' . (!empty($_GET['search']) ? ' по запиту -  <i>' . $_GET['search'] . '</i>' : '');

        return compact('goods', 'data', 'dontShowAside', 'pages');
    }

    public function search(){

        !$this->model && $this->model = Model::instance();

        $search = $this->clearStr($_GET['search'] ?? '');

        $data = [];

        if ($search){

            $goodsIds = $this->model->searchGoodsIds($search);

            if ($goodsIds){

                $data = $this->model->get('goods', [

                   'where' => ['id' => $goodsIds, 'visible'=>1],

                   'operand' => ['IN', '='],
                    'pagination' => [

                        'qty' => $_SESSION['quantities'] ?? QTY,

                        'page' => $this->clearNum($_GET['page'] ?? 1) ? : 1

                    ],

                ], ... [false, false]);
            }
        }

        return $data;

    }

}
