#!/usr/bin/env python3
from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

ROOT = Path("/srv/software_development/forprint-project/forprint_website")
BASE = ROOT / "base"
OUTPUT = BASE / "libraries/generated/forprint_image_dimensions_manifest.php"

EXTENSIONS = {
    ".jpg", ".jpeg", ".png", ".gif", ".webp", ".avif", ".svg",
}

SCAN_ROOTS = [
    BASE / "userfiles",
    BASE / "templates/default/assets/img",
]

# Symbol sprite used through <svg><use ...#symbol>, not through <img>.
IGNORED_PUBLIC_PATHS = {
    "/templates/default/assets/img/icons.svg",
}


def svg_dimensions(path: Path):
    text = path.read_text(
        encoding="utf-8",
        errors="replace",
    )[:30000]

    root = re.search(
        r"<svg\b([^>]*)>",
        text,
        re.I | re.S,
    )
    if not root:
        return None

    attrs = root.group(1)

    def numeric_attr(name: str):
        match = re.search(
            rf'\b{name}\s*=\s*["\']\s*'
            r'([0-9]+(?:\.[0-9]+)?)(?:px)?\s*["\']',
            attrs,
            re.I,
        )
        if not match:
            return None
        value = round(float(match.group(1)))
        return value if value > 0 else None

    width = numeric_attr("width")
    height = numeric_attr("height")

    if width and height:
        return [width, height]

    viewbox = re.search(
        r'\bviewBox\s*=\s*["\']\s*'
        r'([-0-9.]+)[,\s]+'
        r'([-0-9.]+)[,\s]+'
        r'([0-9.]+)[,\s]+'
        r'([0-9.]+)\s*["\']',
        attrs,
        re.I,
    )

    if not viewbox:
        return None

    vb_width = round(float(viewbox.group(3)))
    vb_height = round(float(viewbox.group(4)))

    if vb_width <= 0 or vb_height <= 0:
        return None

    return [
        width or vb_width,
        height or vb_height,
    ]


def raster_dimensions(paths):
    php = r'$paths = json_decode(stream_get_contents(STDIN), true); $out = []; foreach ($paths as $path) { $size = @getimagesize($path); if (is_array($size) && isset($size[0], $size[1]) && (int)$size[0] > 0 && (int)$size[1] > 0) { $out[$path] = [(int)$size[0], (int)$size[1]]; } else { $out[$path] = null; } } echo json_encode($out, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);'

    result = subprocess.run(
        ["php", "-r", php],
        cwd=ROOT,
        input=json.dumps(
            [str(path) for path in paths],
            ensure_ascii=False,
        ),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=600,
    )

    if result.returncode != 0:
        raise RuntimeError(result.stdout + result.stderr)

    return json.loads(result.stdout)


def main():
    files = []

    for scan_root in SCAN_ROOTS:
        if not scan_root.is_dir():
            continue

        for path in scan_root.rglob("*"):
            if (
                path.is_file()
                and not path.is_symlink()
                and path.suffix.lower() in EXTENSIONS
            ):
                files.append(path)

    files = sorted(set(files))

    raster = raster_dimensions(
        [path for path in files if path.suffix.lower() != ".svg"]
    )

    manifest = {}
    ignored = []
    unresolved = []

    for path in files:
        public_path = "/" + path.relative_to(BASE).as_posix()

        if public_path in IGNORED_PUBLIC_PATHS:
            ignored.append(public_path)
            continue

        dimensions = None

        if path.suffix.lower() == ".svg":
            dimensions = svg_dimensions(path)
        else:
            value = raster.get(str(path))
            if isinstance(value, list) and len(value) == 2:
                dimensions = [int(value[0]), int(value[1])]

        if not dimensions:
            unresolved.append(str(path.relative_to(ROOT)))
            continue

        manifest[public_path] = dimensions

    if unresolved:
        print("ForPrint image-dimension manifest rebuild FAILED")
        print(f"unresolved={len(unresolved)}")
        for item in unresolved[:100]:
            print(f"[UNRESOLVED] {item}")
        raise SystemExit(1)

    lines = [
        "<?php",
        "",
        "declare(strict_types=1);",
        "",
        "/*",
        " * Generated by scripts/maintenance/",
        " * rebuild_image_dimensions_manifest.py.",
        " * Do not hand-edit.",
        " * Public <img>-eligible path => [intrinsic width, intrinsic height].",
        " * SVG symbol sprites without root geometry are intentionally excluded.",
        " */",
        "return [",
    ]

    for path, dimensions in sorted(manifest.items()):
        escaped = path.replace("\\", "\\\\").replace("'", "\\'")
        lines.append(
            f"    '{escaped}' => "
            f"[{dimensions[0]}, {dimensions[1]}],"
        )

    lines.extend(["];", ""])

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")

    print("ForPrint image-dimension manifest rebuilt.")
    print(f"files_scanned={len(files)}")
    print(f"manifest_entries={len(manifest)}")
    print(f"ignored_non_img_sprites={len(ignored)}")
    for item in ignored:
        print(f"[IGNORED-SPRITE] {item}")
    print("unresolved=0")
    print(f"output={OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
